development: &development
  adapter: postgresql
  host: localhost
  database: oxcrot_dev
  encoding: unicode
  
test: &test
  adapter: postgresql
  host: localhost
  database: oxcrot_test
  encoding: unicode